//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ogmaneo {

class csogmaneoPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="SWIGRegisterExceptionCallbacks_csogmaneo")]
    public static extern void SWIGRegisterExceptionCallbacks_csogmaneo(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_csogmaneo")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_csogmaneo(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_csogmaneo(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_csogmaneo(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(csogmaneoPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(csogmaneoPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="SWIGRegisterStringCallback_csogmaneo")]
    public static extern void SWIGRegisterStringCallback_csogmaneo(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_csogmaneo(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static csogmaneoPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Clear")]
  public static extern void vectorf_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Add")]
  public static extern void vectorf_Add(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_size")]
  public static extern uint vectorf_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_capacity")]
  public static extern uint vectorf_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_reserve")]
  public static extern void vectorf_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_vectorf__SWIG_0")]
  public static extern global::System.IntPtr new_vectorf__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_vectorf__SWIG_1")]
  public static extern global::System.IntPtr new_vectorf__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_vectorf__SWIG_2")]
  public static extern global::System.IntPtr new_vectorf__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_getitemcopy")]
  public static extern float vectorf_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_getitem")]
  public static extern float vectorf_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_setitem")]
  public static extern void vectorf_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_AddRange")]
  public static extern void vectorf_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_GetRange")]
  public static extern global::System.IntPtr vectorf_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Insert")]
  public static extern void vectorf_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_InsertRange")]
  public static extern void vectorf_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_RemoveAt")]
  public static extern void vectorf_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_RemoveRange")]
  public static extern void vectorf_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Repeat")]
  public static extern global::System.IntPtr vectorf_Repeat(float jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Reverse__SWIG_0")]
  public static extern void vectorf_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Reverse__SWIG_1")]
  public static extern void vectorf_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_SetRange")]
  public static extern void vectorf_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Contains")]
  public static extern bool vectorf_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_IndexOf")]
  public static extern int vectorf_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_LastIndexOf")]
  public static extern int vectorf_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorf_Remove")]
  public static extern bool vectorf_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_vectorf")]
  public static extern void delete_vectorf(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_Clear")]
  public static extern void vectorvf_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_Add")]
  public static extern void vectorvf_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_size")]
  public static extern uint vectorvf_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_capacity")]
  public static extern uint vectorvf_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_reserve")]
  public static extern void vectorvf_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_vectorvf__SWIG_0")]
  public static extern global::System.IntPtr new_vectorvf__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_vectorvf__SWIG_1")]
  public static extern global::System.IntPtr new_vectorvf__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_vectorvf__SWIG_2")]
  public static extern global::System.IntPtr new_vectorvf__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_getitemcopy")]
  public static extern global::System.IntPtr vectorvf_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_getitem")]
  public static extern global::System.IntPtr vectorvf_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_setitem")]
  public static extern void vectorvf_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_AddRange")]
  public static extern void vectorvf_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_GetRange")]
  public static extern global::System.IntPtr vectorvf_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_Insert")]
  public static extern void vectorvf_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_InsertRange")]
  public static extern void vectorvf_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_RemoveAt")]
  public static extern void vectorvf_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_RemoveRange")]
  public static extern void vectorvf_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_Repeat")]
  public static extern global::System.IntPtr vectorvf_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_Reverse__SWIG_0")]
  public static extern void vectorvf_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_Reverse__SWIG_1")]
  public static extern void vectorvf_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_vectorvf_SetRange")]
  public static extern void vectorvf_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_vectorvf")]
  public static extern void delete_vectorvf(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_CL_HPP_MINIMUM_OPENCL_VERSION_get")]
  public static extern int CL_HPP_MINIMUM_OPENCL_VERSION_get();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_CL_HPP_TARGET_OPENCL_VERSION_get")]
  public static extern int CL_HPP_TARGET_OPENCL_VERSION_get();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_SYS_ALLOW_CL_GL_CONTEXT_get")]
  public static extern int SYS_ALLOW_CL_GL_CONTEXT_get();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_create__SWIG_0")]
  public static extern bool ComputeSystem_create__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_create__SWIG_1")]
  public static extern bool ComputeSystem_create__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_create__SWIG_2")]
  public static extern bool ComputeSystem_create__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_create__SWIG_3")]
  public static extern bool ComputeSystem_create__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_getPlatform")]
  public static extern global::System.IntPtr ComputeSystem_getPlatform(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_getDevice")]
  public static extern global::System.IntPtr ComputeSystem_getDevice(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_getContext")]
  public static extern global::System.IntPtr ComputeSystem_getContext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeSystem_getQueue")]
  public static extern global::System.IntPtr ComputeSystem_getQueue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_ComputeSystem")]
  public static extern global::System.IntPtr new_ComputeSystem();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_ComputeSystem")]
  public static extern void delete_ComputeSystem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeProgram_loadFromFile")]
  public static extern bool ComputeProgram_loadFromFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeProgram_loadHierarchyKernel")]
  public static extern bool ComputeProgram_loadHierarchyKernel(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeProgram_loadPredictorKernel")]
  public static extern bool ComputeProgram_loadPredictorKernel(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeProgram_loadSparseFeaturesKernel")]
  public static extern bool ComputeProgram_loadSparseFeaturesKernel(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ComputeProgram_getProgram")]
  public static extern global::System.IntPtr ComputeProgram_getProgram(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_ComputeProgram")]
  public static extern global::System.IntPtr new_ComputeProgram();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_ComputeProgram")]
  public static extern void delete_ComputeProgram(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_activate")]
  public static extern void Hierarchy_activate(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_learn__SWIG_0")]
  public static extern void Hierarchy_learn__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_learn__SWIG_1")]
  public static extern void Hierarchy_learn__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_getInputImagesFeed")]
  public static extern global::System.IntPtr Hierarchy_getInputImagesFeed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_getInputImagesPredict")]
  public static extern global::System.IntPtr Hierarchy_getInputImagesPredict(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_getPredictions")]
  public static extern global::System.IntPtr Hierarchy_getPredictions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_getPredictor")]
  public static extern global::System.IntPtr Hierarchy_getPredictor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_readChunkStates")]
  public static extern void Hierarchy_readChunkStates(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_load")]
  public static extern void Hierarchy_load(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Hierarchy_save")]
  public static extern void Hierarchy_save(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Hierarchy")]
  public static extern global::System.IntPtr new_Hierarchy();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_Hierarchy")]
  public static extern void delete_Hierarchy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2i_x_set")]
  public static extern void Vec2i_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2i_x_get")]
  public static extern int Vec2i_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2i_y_set")]
  public static extern void Vec2i_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2i_y_get")]
  public static extern int Vec2i_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Vec2i__SWIG_0")]
  public static extern global::System.IntPtr new_Vec2i__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Vec2i__SWIG_1")]
  public static extern global::System.IntPtr new_Vec2i__SWIG_1(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_Vec2i")]
  public static extern void delete_Vec2i(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2f_x_set")]
  public static extern void Vec2f_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2f_x_get")]
  public static extern float Vec2f_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2f_y_set")]
  public static extern void Vec2f_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Vec2f_y_get")]
  public static extern float Vec2f_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Vec2f__SWIG_0")]
  public static extern global::System.IntPtr new_Vec2f__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Vec2f__SWIG_1")]
  public static extern global::System.IntPtr new_Vec2f__SWIG_1(float jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Vec2f__SWIG_2")]
  public static extern global::System.IntPtr new_Vec2f__SWIG_2(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_Vec2f")]
  public static extern void delete_Vec2f(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Resources__SWIG_0")]
  public static extern global::System.IntPtr new_Resources__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Resources__SWIG_1")]
  public static extern global::System.IntPtr new_Resources__SWIG_1(int jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Resources__SWIG_2")]
  public static extern global::System.IntPtr new_Resources__SWIG_2(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Resources__SWIG_3")]
  public static extern global::System.IntPtr new_Resources__SWIG_3(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Resources_create__SWIG_0")]
  public static extern void Resources_create__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Resources_create__SWIG_1")]
  public static extern void Resources_create__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Resources_create__SWIG_2")]
  public static extern void Resources_create__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Resources_getComputeSystem")]
  public static extern global::System.IntPtr Resources_getComputeSystem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Resources_getPrograms")]
  public static extern global::System.IntPtr Resources_getPrograms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_Resources")]
  public static extern void delete_Resources(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_ValueField2D__SWIG_0")]
  public static extern global::System.IntPtr new_ValueField2D__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_ValueField2D__SWIG_1")]
  public static extern global::System.IntPtr new_ValueField2D__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_ValueField2D__SWIG_2")]
  public static extern global::System.IntPtr new_ValueField2D__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_create__SWIG_0")]
  public static extern void ValueField2D_create__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_create__SWIG_1")]
  public static extern void ValueField2D_create__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_getValue")]
  public static extern float ValueField2D_getValue(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_setValue")]
  public static extern void ValueField2D_setValue(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_getSize")]
  public static extern global::System.IntPtr ValueField2D_getSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_getData")]
  public static extern global::System.IntPtr ValueField2D_getData(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_setValues")]
  public static extern void ValueField2D_setValues(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_load")]
  public static extern void ValueField2D_load(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ValueField2D_save")]
  public static extern global::System.IntPtr ValueField2D_save(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_ValueField2D")]
  public static extern void delete_ValueField2D(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier__boolTrue_get")]
  public static extern string ParameterModifier__boolTrue_get();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier__boolFalse_get")]
  public static extern string ParameterModifier__boolFalse_get();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_setValue__SWIG_0")]
  public static extern global::System.IntPtr ParameterModifier_setValue__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_setValueBool")]
  public static extern global::System.IntPtr ParameterModifier_setValueBool(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_setValue__SWIG_1")]
  public static extern global::System.IntPtr ParameterModifier_setValue__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_setValue__SWIG_2")]
  public static extern global::System.IntPtr ParameterModifier_setValue__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_setValue__SWIG_3")]
  public static extern global::System.IntPtr ParameterModifier_setValue__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_setValues")]
  public static extern global::System.IntPtr ParameterModifier_setValues(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_parseVec2i")]
  public static extern global::System.IntPtr ParameterModifier_parseVec2i(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_parseVec2f")]
  public static extern global::System.IntPtr ParameterModifier_parseVec2f(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_parseBool")]
  public static extern bool ParameterModifier_parseBool(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_load")]
  public static extern void ParameterModifier_load(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_ParameterModifier_save")]
  public static extern global::System.IntPtr ParameterModifier_save(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_ParameterModifier")]
  public static extern global::System.IntPtr new_ParameterModifier();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_ParameterModifier")]
  public static extern void delete_ParameterModifier(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_InputLayer")]
  public static extern global::System.IntPtr new_InputLayer();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_InputLayer")]
  public static extern void delete_InputLayer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_HigherLayer")]
  public static extern global::System.IntPtr new_HigherLayer();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_HigherLayer")]
  public static extern void delete_HigherLayer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_initialize")]
  public static extern void Architect_initialize(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_addInputLayer__SWIG_0")]
  public static extern global::System.IntPtr Architect_addInputLayer__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_addInputLayer__SWIG_1")]
  public static extern global::System.IntPtr Architect_addInputLayer__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_addInputLayer__SWIG_2")]
  public static extern global::System.IntPtr Architect_addInputLayer__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_addHigherLayer")]
  public static extern global::System.IntPtr Architect_addHigherLayer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_generateHierarchy__SWIG_0")]
  public static extern global::System.IntPtr Architect_generateHierarchy__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_generateHierarchy__SWIG_1")]
  public static extern global::System.IntPtr Architect_generateHierarchy__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_load")]
  public static extern void Architect_load(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_Architect_save")]
  public static extern void Architect_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_new_Architect")]
  public static extern global::System.IntPtr new_Architect();

  [global::System.Runtime.InteropServices.DllImport("CsOgmaNeo", EntryPoint="CSharp_ogmaneo_delete_Architect")]
  public static extern void delete_Architect(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
