//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ogmaneo {

public class csogmaneo {
  public static readonly int CL_HPP_MINIMUM_OPENCL_VERSION = csogmaneoPINVOKE.CL_HPP_MINIMUM_OPENCL_VERSION_get();
  public static readonly int CL_HPP_TARGET_OPENCL_VERSION = csogmaneoPINVOKE.CL_HPP_TARGET_OPENCL_VERSION_get();
  public static readonly int SYS_ALLOW_CL_GL_CONTEXT = csogmaneoPINVOKE.SYS_ALLOW_CL_GL_CONTEXT_get();
}

}
