//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ogmaneo {

public class ParameterModifier : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParameterModifier(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ParameterModifier obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParameterModifier() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csogmaneoPINVOKE.delete_ParameterModifier(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static string _boolTrue {
    get {
      string ret = csogmaneoPINVOKE.ParameterModifier__boolTrue_get();
      return ret;
    } 
  }

  public static string _boolFalse {
    get {
      string ret = csogmaneoPINVOKE.ParameterModifier__boolFalse_get();
      return ret;
    } 
  }

  public ParameterModifier setValue(string name, string value) {
    ParameterModifier ret = new ParameterModifier(csogmaneoPINVOKE.ParameterModifier_setValue__SWIG_0(swigCPtr, name, value), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParameterModifier setValueBool(string name, bool value) {
    ParameterModifier ret = new ParameterModifier(csogmaneoPINVOKE.ParameterModifier_setValueBool(swigCPtr, name, value), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParameterModifier setValue(string name, float value) {
    ParameterModifier ret = new ParameterModifier(csogmaneoPINVOKE.ParameterModifier_setValue__SWIG_1(swigCPtr, name, value), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParameterModifier setValue(string name, Vec2i size) {
    ParameterModifier ret = new ParameterModifier(csogmaneoPINVOKE.ParameterModifier_setValue__SWIG_2(swigCPtr, name, Vec2i.getCPtr(size)), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParameterModifier setValue(string name, Vec2f size) {
    ParameterModifier ret = new ParameterModifier(csogmaneoPINVOKE.ParameterModifier_setValue__SWIG_3(swigCPtr, name, Vec2f.getCPtr(size)), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParameterModifier setValues(SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t namesValues) {
    ParameterModifier ret = new ParameterModifier(csogmaneoPINVOKE.ParameterModifier_setValues(swigCPtr, SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t.getCPtr(namesValues)), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Vec2i parseVec2i(string s) {
    Vec2i ret = new Vec2i(csogmaneoPINVOKE.ParameterModifier_parseVec2i(s), true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Vec2f parseVec2f(string s) {
    Vec2f ret = new Vec2f(csogmaneoPINVOKE.ParameterModifier_parseVec2f(s), true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool parseBool(string s) {
    bool ret = csogmaneoPINVOKE.ParameterModifier_parseBool(s);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void load(SWIGTYPE_p_ogmaneo__schemas__ParameterModifier fbParameterModifier, ComputeSystem cs) {
    csogmaneoPINVOKE.ParameterModifier_load(swigCPtr, SWIGTYPE_p_ogmaneo__schemas__ParameterModifier.getCPtr(fbParameterModifier), ComputeSystem.getCPtr(cs));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_flatbuffers__OffsetT_ogmaneo__schemas__ParameterModifier_t save(SWIGTYPE_p_flatbuffers__FlatBufferBuilder builder, ComputeSystem cs) {
    SWIGTYPE_p_flatbuffers__OffsetT_ogmaneo__schemas__ParameterModifier_t ret = new SWIGTYPE_p_flatbuffers__OffsetT_ogmaneo__schemas__ParameterModifier_t(csogmaneoPINVOKE.ParameterModifier_save(swigCPtr, SWIGTYPE_p_flatbuffers__FlatBufferBuilder.getCPtr(builder), ComputeSystem.getCPtr(cs)), true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParameterModifier() : this(csogmaneoPINVOKE.new_ParameterModifier(), true) {
  }

}

}
