//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ogmaneo {

public class ValueField2D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ValueField2D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ValueField2D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ValueField2D() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csogmaneoPINVOKE.delete_ValueField2D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ValueField2D() : this(csogmaneoPINVOKE.new_ValueField2D__SWIG_0(), true) {
  }

  public ValueField2D(Vec2i size, float defVal) : this(csogmaneoPINVOKE.new_ValueField2D__SWIG_1(Vec2i.getCPtr(size), defVal), true) {
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public ValueField2D(Vec2i size) : this(csogmaneoPINVOKE.new_ValueField2D__SWIG_2(Vec2i.getCPtr(size)), true) {
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void create(Vec2i size, float defVal) {
    csogmaneoPINVOKE.ValueField2D_create__SWIG_0(swigCPtr, Vec2i.getCPtr(size), defVal);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void create(Vec2i size) {
    csogmaneoPINVOKE.ValueField2D_create__SWIG_1(swigCPtr, Vec2i.getCPtr(size));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getValue(Vec2i pos) {
    float ret = csogmaneoPINVOKE.ValueField2D_getValue(swigCPtr, Vec2i.getCPtr(pos));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setValue(Vec2i pos, float value) {
    csogmaneoPINVOKE.ValueField2D_setValue(swigCPtr, Vec2i.getCPtr(pos), value);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec2i getSize() {
    Vec2i ret = new Vec2i(csogmaneoPINVOKE.ValueField2D_getSize(swigCPtr), true);
    return ret;
  }

  public vectorf getData() {
    vectorf ret = new vectorf(csogmaneoPINVOKE.ValueField2D_getData(swigCPtr), false);
    return ret;
  }

  public void setValues(vectorf values) {
    csogmaneoPINVOKE.ValueField2D_setValues(swigCPtr, vectorf.getCPtr(values));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void load(SWIGTYPE_p_ogmaneo__schemas__ValueField2D fbValueField2D, ComputeSystem cs) {
    csogmaneoPINVOKE.ValueField2D_load(swigCPtr, SWIGTYPE_p_ogmaneo__schemas__ValueField2D.getCPtr(fbValueField2D), ComputeSystem.getCPtr(cs));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_flatbuffers__OffsetT_ogmaneo__schemas__ValueField2D_t save(SWIGTYPE_p_flatbuffers__FlatBufferBuilder builder, ComputeSystem cs) {
    SWIGTYPE_p_flatbuffers__OffsetT_ogmaneo__schemas__ValueField2D_t ret = new SWIGTYPE_p_flatbuffers__OffsetT_ogmaneo__schemas__ValueField2D_t(csogmaneoPINVOKE.ValueField2D_save(swigCPtr, SWIGTYPE_p_flatbuffers__FlatBufferBuilder.getCPtr(builder), ComputeSystem.getCPtr(cs)), true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
