//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ogmaneo {

public class vectorvf : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<ValueField2D>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vectorvf(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vectorvf obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vectorvf() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csogmaneoPINVOKE.delete_vectorvf(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vectorvf(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ValueField2D element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ValueField2D this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ValueField2D[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ValueField2D[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ValueField2D[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<ValueField2D> global::System.Collections.Generic.IEnumerable<ValueField2D>.GetEnumerator() {
    return new vectorvfEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new vectorvfEnumerator(this);
  }

  public vectorvfEnumerator GetEnumerator() {
    return new vectorvfEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vectorvfEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ValueField2D>
  {
    private vectorvf collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vectorvfEnumerator(vectorvf collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ValueField2D Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ValueField2D)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    csogmaneoPINVOKE.vectorvf_Clear(swigCPtr);
  }

  public void Add(ValueField2D x) {
    csogmaneoPINVOKE.vectorvf_Add(swigCPtr, ValueField2D.getCPtr(x));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = csogmaneoPINVOKE.vectorvf_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = csogmaneoPINVOKE.vectorvf_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    csogmaneoPINVOKE.vectorvf_reserve(swigCPtr, n);
  }

  public vectorvf() : this(csogmaneoPINVOKE.new_vectorvf__SWIG_0(), true) {
  }

  public vectorvf(vectorvf other) : this(csogmaneoPINVOKE.new_vectorvf__SWIG_1(vectorvf.getCPtr(other)), true) {
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public vectorvf(int capacity) : this(csogmaneoPINVOKE.new_vectorvf__SWIG_2(capacity), true) {
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  private ValueField2D getitemcopy(int index) {
    ValueField2D ret = new ValueField2D(csogmaneoPINVOKE.vectorvf_getitemcopy(swigCPtr, index), true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ValueField2D getitem(int index) {
    ValueField2D ret = new ValueField2D(csogmaneoPINVOKE.vectorvf_getitem(swigCPtr, index), false);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ValueField2D val) {
    csogmaneoPINVOKE.vectorvf_setitem(swigCPtr, index, ValueField2D.getCPtr(val));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vectorvf values) {
    csogmaneoPINVOKE.vectorvf_AddRange(swigCPtr, vectorvf.getCPtr(values));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public vectorvf GetRange(int index, int count) {
    global::System.IntPtr cPtr = csogmaneoPINVOKE.vectorvf_GetRange(swigCPtr, index, count);
    vectorvf ret = (cPtr == global::System.IntPtr.Zero) ? null : new vectorvf(cPtr, true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ValueField2D x) {
    csogmaneoPINVOKE.vectorvf_Insert(swigCPtr, index, ValueField2D.getCPtr(x));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vectorvf values) {
    csogmaneoPINVOKE.vectorvf_InsertRange(swigCPtr, index, vectorvf.getCPtr(values));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    csogmaneoPINVOKE.vectorvf_RemoveAt(swigCPtr, index);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    csogmaneoPINVOKE.vectorvf_RemoveRange(swigCPtr, index, count);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static vectorvf Repeat(ValueField2D value, int count) {
    global::System.IntPtr cPtr = csogmaneoPINVOKE.vectorvf_Repeat(ValueField2D.getCPtr(value), count);
    vectorvf ret = (cPtr == global::System.IntPtr.Zero) ? null : new vectorvf(cPtr, true);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    csogmaneoPINVOKE.vectorvf_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    csogmaneoPINVOKE.vectorvf_Reverse__SWIG_1(swigCPtr, index, count);
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vectorvf values) {
    csogmaneoPINVOKE.vectorvf_SetRange(swigCPtr, index, vectorvf.getCPtr(values));
    if (csogmaneoPINVOKE.SWIGPendingException.Pending) throw csogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
