//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class eogmaneo {
  public static StdVecf whiten(StdVecf src, int width, int radius, float strength, ComputeSystem system, int chunkSize) {
    StdVecf ret = new StdVecf(eogmaneoPINVOKE.whiten__SWIG_0(StdVecf.getCPtr(src), width, radius, strength, ComputeSystem.getCPtr(system), chunkSize), true);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void whiten(StdVecf src, StdVecf dest, int width, int radius, float strength, int cx, int cy, int chunkSize) {
    eogmaneoPINVOKE.whiten__SWIG_1(StdVecf.getCPtr(src), StdVecf.getCPtr(dest), width, radius, strength, cx, cy, chunkSize);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static StdVecf sobel(StdVecf src, int width, float clip, ComputeSystem system, int chunkSize) {
    StdVecf ret = new StdVecf(eogmaneoPINVOKE.sobel(StdVecf.getCPtr(src), width, clip, ComputeSystem.getCPtr(system), chunkSize), true);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void sobelX(StdVecf src, StdVecf dest, int width, int cx, int cy, int chunkSize) {
    eogmaneoPINVOKE.sobelX(StdVecf.getCPtr(src), StdVecf.getCPtr(dest), width, cx, cy, chunkSize);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void sobelY(StdVecf src, StdVecf dest, int width, int cx, int cy, int chunkSize) {
    eogmaneoPINVOKE.sobelY(StdVecf.getCPtr(src), StdVecf.getCPtr(dest), width, cx, cy, chunkSize);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void sobelCombine(StdVecf srcX, StdVecf srcY, StdVecf dest, int width, float clip, int cx, int cy, int chunkSize) {
    eogmaneoPINVOKE.sobelCombine(StdVecf.getCPtr(srcX), StdVecf.getCPtr(srcY), StdVecf.getCPtr(dest), width, clip, cx, cy, chunkSize);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
