//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class LayerDesc : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LayerDesc(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LayerDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LayerDesc() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_LayerDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int _width {
    set {
      eogmaneoPINVOKE.LayerDesc__width_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__width_get(swigCPtr);
      return ret;
    } 
  }

  public int _height {
    set {
      eogmaneoPINVOKE.LayerDesc__height_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__height_get(swigCPtr);
      return ret;
    } 
  }

  public int _chunkSize {
    set {
      eogmaneoPINVOKE.LayerDesc__chunkSize_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__chunkSize_get(swigCPtr);
      return ret;
    } 
  }

  public int _forwardRadius {
    set {
      eogmaneoPINVOKE.LayerDesc__forwardRadius_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__forwardRadius_get(swigCPtr);
      return ret;
    } 
  }

  public int _backwardRadius {
    set {
      eogmaneoPINVOKE.LayerDesc__backwardRadius_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__backwardRadius_get(swigCPtr);
      return ret;
    } 
  }

  public int _ticksPerUpdate {
    set {
      eogmaneoPINVOKE.LayerDesc__ticksPerUpdate_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__ticksPerUpdate_get(swigCPtr);
      return ret;
    } 
  }

  public int _temporalHorizon {
    set {
      eogmaneoPINVOKE.LayerDesc__temporalHorizon_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__temporalHorizon_get(swigCPtr);
      return ret;
    } 
  }

  public float _alpha {
    set {
      eogmaneoPINVOKE.LayerDesc__alpha_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.LayerDesc__alpha_get(swigCPtr);
      return ret;
    } 
  }

  public float _beta {
    set {
      eogmaneoPINVOKE.LayerDesc__beta_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.LayerDesc__beta_get(swigCPtr);
      return ret;
    } 
  }

  public float _delta {
    set {
      eogmaneoPINVOKE.LayerDesc__delta_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.LayerDesc__delta_get(swigCPtr);
      return ret;
    } 
  }

  public float _gamma {
    set {
      eogmaneoPINVOKE.LayerDesc__gamma_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.LayerDesc__gamma_get(swigCPtr);
      return ret;
    } 
  }

  public float _epsilon {
    set {
      eogmaneoPINVOKE.LayerDesc__epsilon_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.LayerDesc__epsilon_get(swigCPtr);
      return ret;
    } 
  }

  public int _maxReplaySamples {
    set {
      eogmaneoPINVOKE.LayerDesc__maxReplaySamples_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__maxReplaySamples_get(swigCPtr);
      return ret;
    } 
  }

  public int _replayIter {
    set {
      eogmaneoPINVOKE.LayerDesc__replayIter_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.LayerDesc__replayIter_get(swigCPtr);
      return ret;
    } 
  }

  public LayerDesc() : this(eogmaneoPINVOKE.new_LayerDesc(), true) {
  }

}

}
