//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class Network : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Network(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Network obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Network() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_Network(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_sf__Uint16 _numLayers {
    set {
      eogmaneoPINVOKE.Network__numLayers_set(swigCPtr, SWIGTYPE_p_sf__Uint16.getCPtr(value));
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_sf__Uint16 ret = new SWIGTYPE_p_sf__Uint16(eogmaneoPINVOKE.Network__numLayers_get(swigCPtr), true);
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_sf__Uint16 _numWeightSets {
    set {
      eogmaneoPINVOKE.Network__numWeightSets_set(swigCPtr, SWIGTYPE_p_sf__Uint16.getCPtr(value));
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_sf__Uint16 ret = new SWIGTYPE_p_sf__Uint16(eogmaneoPINVOKE.Network__numWeightSets_get(swigCPtr), true);
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_eogmaneo__SDR_t _sdrs {
    set {
      eogmaneoPINVOKE.Network__sdrs_set(swigCPtr, SWIGTYPE_p_std__vectorT_eogmaneo__SDR_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.Network__sdrs_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_eogmaneo__SDR_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_eogmaneo__SDR_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_eogmaneo__WeightSet_t _weightSets {
    set {
      eogmaneoPINVOKE.Network__weightSets_set(swigCPtr, SWIGTYPE_p_std__vectorT_eogmaneo__WeightSet_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.Network__weightSets_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_eogmaneo__WeightSet_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_eogmaneo__WeightSet_t(cPtr, false);
      return ret;
    } 
  }

  public Network() : this(eogmaneoPINVOKE.new_Network(), true) {
  }

}

}
