//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class ReplaySample : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ReplaySample(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ReplaySample obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ReplaySample() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_ReplaySample(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Std2DVeci _predictionsPrev {
    set {
      eogmaneoPINVOKE.ReplaySample__predictionsPrev_set(swigCPtr, Std2DVeci.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.ReplaySample__predictionsPrev_get(swigCPtr);
      Std2DVeci ret = (cPtr == global::System.IntPtr.Zero) ? null : new Std2DVeci(cPtr, false);
      return ret;
    } 
  }

  public Std2DVeci _feedBackPrev {
    set {
      eogmaneoPINVOKE.ReplaySample__feedBackPrev_set(swigCPtr, Std2DVeci.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.ReplaySample__feedBackPrev_get(swigCPtr);
      Std2DVeci ret = (cPtr == global::System.IntPtr.Zero) ? null : new Std2DVeci(cPtr, false);
      return ret;
    } 
  }

  public float _reward {
    set {
      eogmaneoPINVOKE.ReplaySample__reward_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.ReplaySample__reward_get(swigCPtr);
      return ret;
    } 
  }

  public ReplaySample() : this(eogmaneoPINVOKE.new_ReplaySample(), true) {
  }

}

}
