//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class SDR : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SDR(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SDR obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SDR() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_SDR(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_sf__Uint16 _chunkSize {
    set {
      eogmaneoPINVOKE.SDR__chunkSize_set(swigCPtr, SWIGTYPE_p_sf__Uint16.getCPtr(value));
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_sf__Uint16 ret = new SWIGTYPE_p_sf__Uint16(eogmaneoPINVOKE.SDR__chunkSize_get(swigCPtr), true);
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_sf__Uint16 _width {
    set {
      eogmaneoPINVOKE.SDR__width_set(swigCPtr, SWIGTYPE_p_sf__Uint16.getCPtr(value));
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_sf__Uint16 ret = new SWIGTYPE_p_sf__Uint16(eogmaneoPINVOKE.SDR__width_get(swigCPtr), true);
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_sf__Uint16 _height {
    set {
      eogmaneoPINVOKE.SDR__height_set(swigCPtr, SWIGTYPE_p_sf__Uint16.getCPtr(value));
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_sf__Uint16 ret = new SWIGTYPE_p_sf__Uint16(eogmaneoPINVOKE.SDR__height_get(swigCPtr), true);
      if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_sf__Uint16_t _chunkIndices {
    set {
      eogmaneoPINVOKE.SDR__chunkIndices_set(swigCPtr, SWIGTYPE_p_std__vectorT_sf__Uint16_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.SDR__chunkIndices_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_sf__Uint16_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_sf__Uint16_t(cPtr, false);
      return ret;
    } 
  }

  public SDR() : this(eogmaneoPINVOKE.new_SDR(), true) {
  }

}

}
