//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class SobelCombineWorkItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SobelCombineWorkItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SobelCombineWorkItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SobelCombineWorkItem() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_SobelCombineWorkItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StdVecf _psrcX {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__psrcX_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.SobelCombineWorkItem__psrcX_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public StdVecf _psrcY {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__psrcY_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.SobelCombineWorkItem__psrcY_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public StdVecf _pdest {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__pdest_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.SobelCombineWorkItem__pdest_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public int _cx {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__cx_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelCombineWorkItem__cx_get(swigCPtr);
      return ret;
    } 
  }

  public int _cy {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__cy_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelCombineWorkItem__cy_get(swigCPtr);
      return ret;
    } 
  }

  public int _width {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__width_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelCombineWorkItem__width_get(swigCPtr);
      return ret;
    } 
  }

  public float _clip {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__clip_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.SobelCombineWorkItem__clip_get(swigCPtr);
      return ret;
    } 
  }

  public int _chunkSize {
    set {
      eogmaneoPINVOKE.SobelCombineWorkItem__chunkSize_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelCombineWorkItem__chunkSize_get(swigCPtr);
      return ret;
    } 
  }

  public SobelCombineWorkItem() : this(eogmaneoPINVOKE.new_SobelCombineWorkItem(), true) {
  }

  public void run(uint threadIndex) {
    eogmaneoPINVOKE.SobelCombineWorkItem_run(swigCPtr, threadIndex);
  }

}

}
