//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class SobelXWorkItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SobelXWorkItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SobelXWorkItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SobelXWorkItem() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_SobelXWorkItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StdVecf _psrc {
    set {
      eogmaneoPINVOKE.SobelXWorkItem__psrc_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.SobelXWorkItem__psrc_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public StdVecf _pdest {
    set {
      eogmaneoPINVOKE.SobelXWorkItem__pdest_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.SobelXWorkItem__pdest_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public int _cx {
    set {
      eogmaneoPINVOKE.SobelXWorkItem__cx_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelXWorkItem__cx_get(swigCPtr);
      return ret;
    } 
  }

  public int _cy {
    set {
      eogmaneoPINVOKE.SobelXWorkItem__cy_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelXWorkItem__cy_get(swigCPtr);
      return ret;
    } 
  }

  public int _width {
    set {
      eogmaneoPINVOKE.SobelXWorkItem__width_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelXWorkItem__width_get(swigCPtr);
      return ret;
    } 
  }

  public int _chunkSize {
    set {
      eogmaneoPINVOKE.SobelXWorkItem__chunkSize_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.SobelXWorkItem__chunkSize_get(swigCPtr);
      return ret;
    } 
  }

  public SobelXWorkItem() : this(eogmaneoPINVOKE.new_SobelXWorkItem(), true) {
  }

  public void run(uint threadIndex) {
    eogmaneoPINVOKE.SobelXWorkItem_run(swigCPtr, threadIndex);
  }

}

}
