//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class StdPairi : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StdPairi(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StdPairi obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StdPairi() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_StdPairi(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StdPairi() : this(eogmaneoPINVOKE.new_StdPairi__SWIG_0(), true) {
  }

  public StdPairi(int t, int u) : this(eogmaneoPINVOKE.new_StdPairi__SWIG_1(t, u), true) {
  }

  public StdPairi(StdPairi p) : this(eogmaneoPINVOKE.new_StdPairi__SWIG_2(StdPairi.getCPtr(p)), true) {
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public int first {
    set {
      eogmaneoPINVOKE.StdPairi_first_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.StdPairi_first_get(swigCPtr);
      return ret;
    } 
  }

  public int second {
    set {
      eogmaneoPINVOKE.StdPairi_second_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.StdPairi_second_get(swigCPtr);
      return ret;
    } 
  }

}

}
