//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class StdVeci : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<int>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StdVeci(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StdVeci obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StdVeci() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_StdVeci(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StdVeci(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (int element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public int this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(int[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(int[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, int[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<int> global::System.Collections.Generic.IEnumerable<int>.GetEnumerator() {
    return new StdVeciEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new StdVeciEnumerator(this);
  }

  public StdVeciEnumerator GetEnumerator() {
    return new StdVeciEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class StdVeciEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<int>
  {
    private StdVeci collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public StdVeciEnumerator(StdVeci collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public int Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (int)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    eogmaneoPINVOKE.StdVeci_Clear(swigCPtr);
  }

  public void Add(int x) {
    eogmaneoPINVOKE.StdVeci_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = eogmaneoPINVOKE.StdVeci_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = eogmaneoPINVOKE.StdVeci_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    eogmaneoPINVOKE.StdVeci_reserve(swigCPtr, n);
  }

  public StdVeci() : this(eogmaneoPINVOKE.new_StdVeci__SWIG_0(), true) {
  }

  public StdVeci(StdVeci other) : this(eogmaneoPINVOKE.new_StdVeci__SWIG_1(StdVeci.getCPtr(other)), true) {
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public StdVeci(int capacity) : this(eogmaneoPINVOKE.new_StdVeci__SWIG_2(capacity), true) {
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  private int getitemcopy(int index) {
    int ret = eogmaneoPINVOKE.StdVeci_getitemcopy(swigCPtr, index);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private int getitem(int index) {
    int ret = eogmaneoPINVOKE.StdVeci_getitem(swigCPtr, index);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, int val) {
    eogmaneoPINVOKE.StdVeci_setitem(swigCPtr, index, val);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(StdVeci values) {
    eogmaneoPINVOKE.StdVeci_AddRange(swigCPtr, StdVeci.getCPtr(values));
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public StdVeci GetRange(int index, int count) {
    global::System.IntPtr cPtr = eogmaneoPINVOKE.StdVeci_GetRange(swigCPtr, index, count);
    StdVeci ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVeci(cPtr, true);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, int x) {
    eogmaneoPINVOKE.StdVeci_Insert(swigCPtr, index, x);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, StdVeci values) {
    eogmaneoPINVOKE.StdVeci_InsertRange(swigCPtr, index, StdVeci.getCPtr(values));
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    eogmaneoPINVOKE.StdVeci_RemoveAt(swigCPtr, index);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    eogmaneoPINVOKE.StdVeci_RemoveRange(swigCPtr, index, count);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static StdVeci Repeat(int value, int count) {
    global::System.IntPtr cPtr = eogmaneoPINVOKE.StdVeci_Repeat(value, count);
    StdVeci ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVeci(cPtr, true);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    eogmaneoPINVOKE.StdVeci_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    eogmaneoPINVOKE.StdVeci_Reverse__SWIG_1(swigCPtr, index, count);
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, StdVeci values) {
    eogmaneoPINVOKE.StdVeci_SetRange(swigCPtr, index, StdVeci.getCPtr(values));
    if (eogmaneoPINVOKE.SWIGPendingException.Pending) throw eogmaneoPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(int value) {
    bool ret = eogmaneoPINVOKE.StdVeci_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(int value) {
    int ret = eogmaneoPINVOKE.StdVeci_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(int value) {
    int ret = eogmaneoPINVOKE.StdVeci_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(int value) {
    bool ret = eogmaneoPINVOKE.StdVeci_Remove(swigCPtr, value);
    return ret;
  }

}

}
