//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class VisibleLayerDesc : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VisibleLayerDesc(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisibleLayerDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VisibleLayerDesc() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_VisibleLayerDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int _width {
    set {
      eogmaneoPINVOKE.VisibleLayerDesc__width_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.VisibleLayerDesc__width_get(swigCPtr);
      return ret;
    } 
  }

  public int _height {
    set {
      eogmaneoPINVOKE.VisibleLayerDesc__height_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.VisibleLayerDesc__height_get(swigCPtr);
      return ret;
    } 
  }

  public int _chunkSize {
    set {
      eogmaneoPINVOKE.VisibleLayerDesc__chunkSize_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.VisibleLayerDesc__chunkSize_get(swigCPtr);
      return ret;
    } 
  }

  public int _forwardRadius {
    set {
      eogmaneoPINVOKE.VisibleLayerDesc__forwardRadius_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.VisibleLayerDesc__forwardRadius_get(swigCPtr);
      return ret;
    } 
  }

  public int _backwardRadius {
    set {
      eogmaneoPINVOKE.VisibleLayerDesc__backwardRadius_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.VisibleLayerDesc__backwardRadius_get(swigCPtr);
      return ret;
    } 
  }

  public bool _predict {
    set {
      eogmaneoPINVOKE.VisibleLayerDesc__predict_set(swigCPtr, value);
    } 
    get {
      bool ret = eogmaneoPINVOKE.VisibleLayerDesc__predict_get(swigCPtr);
      return ret;
    } 
  }

  public VisibleLayerDesc() : this(eogmaneoPINVOKE.new_VisibleLayerDesc(), true) {
  }

}

}
