//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eogmaneo {

public class WhitenerWorkItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WhitenerWorkItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WhitenerWorkItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~WhitenerWorkItem() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          eogmaneoPINVOKE.delete_WhitenerWorkItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StdVecf _psrc {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__psrc_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.WhitenerWorkItem__psrc_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public StdVecf _pdest {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__pdest_set(swigCPtr, StdVecf.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = eogmaneoPINVOKE.WhitenerWorkItem__pdest_get(swigCPtr);
      StdVecf ret = (cPtr == global::System.IntPtr.Zero) ? null : new StdVecf(cPtr, false);
      return ret;
    } 
  }

  public int _cx {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__cx_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.WhitenerWorkItem__cx_get(swigCPtr);
      return ret;
    } 
  }

  public int _cy {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__cy_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.WhitenerWorkItem__cy_get(swigCPtr);
      return ret;
    } 
  }

  public int _width {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__width_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.WhitenerWorkItem__width_get(swigCPtr);
      return ret;
    } 
  }

  public int _radius {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__radius_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.WhitenerWorkItem__radius_get(swigCPtr);
      return ret;
    } 
  }

  public float _strength {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__strength_set(swigCPtr, value);
    } 
    get {
      float ret = eogmaneoPINVOKE.WhitenerWorkItem__strength_get(swigCPtr);
      return ret;
    } 
  }

  public int _chunkSize {
    set {
      eogmaneoPINVOKE.WhitenerWorkItem__chunkSize_set(swigCPtr, value);
    } 
    get {
      int ret = eogmaneoPINVOKE.WhitenerWorkItem__chunkSize_get(swigCPtr);
      return ret;
    } 
  }

  public WhitenerWorkItem() : this(eogmaneoPINVOKE.new_WhitenerWorkItem(), true) {
  }

  public void run(uint threadIndex) {
    eogmaneoPINVOKE.WhitenerWorkItem_run(swigCPtr, threadIndex);
  }

}

}
